- name: ADD CONFIGURATION PEER TO WIREGUARD SERVER
  become: true
  ansible.builtin.shell:
    cmd: |
      wg set server peer {{ hostvars[item]['public_' ~ item ~ '_key'] }} \
        allowed-ips {{ vars['VPN_clients'][item] }}
  loop: "{{ groups['VPN_clients'] }}"