- name: STARTING CONFIGURATION FOR CLIENTS
  debug:
    msg: "CLIENT: {{ inventory_hostname }}"

- name: INSTALL RESOLVCONF
  become: true
  ansible.builtin.apt:
    name: resolvconf
    state: latest

- name: COPY CLIENT MAIN CONFIGURATON
  become: true
  ansible.builtin.template:
    src: client_configuration.primary
    dest: /etc/wireguard/client.conf
    mode: 0600
